apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anvil.fullname" . }}-web
  labels:
    {{- include "anvil.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "anvil.componentLabels" (merge (dict "component" "web") .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "anvil.componentLabels" (merge (dict "component" "web") .) | nindent 8 }}
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "anvil.image" (dict "image" .Values.image.web "default" .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: API_UPSTREAM
              value: {{ default (printf "http://%s-api:%v" (include "anvil.fullname" .) .Values.api.service.port) .Values.web.apiUpstream | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "anvil.fullname" . }}-web
  labels:
    {{- include "anvil.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
  selector:
    {{- include "anvil.componentLabels" (merge (dict "component" "web") .) | nindent 4 }}
{{- if .Values.web.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "anvil.fullname" . }}-web
  labels:
    {{- include "anvil.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.web.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.web.ingress.className }}
  ingressClassName: {{ .Values.web.ingress.className }}
  {{- end }}
  {{- with .Values.web.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.web.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "anvil.fullname" $ }}-web
                port:
                  number: {{ $.Values.web.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
